// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3

package types

type TMDBBySearchEngineRequst struct {
	Query string `form:"query"`
}

type TMDBBySearchEngineResponse struct {
	Name string `json:"name"`
}
