// Code generated by goctl. DO NOT EDIT.
package types

type Request struct {
	Name string `path:"name,options=you|me"`
}

type Response struct {
	Message string `json:"message"`
}

type FilesRequest struct {
	Path string `form:"path"`
}

type FilesResponse struct {
	Files []FileInfo `json:"files"`
}

type FileInfo struct {
	ID          string `json:"id"`
	Name        string `json:"name"`
	Type        string `json:"type"`
	Size        int64  `json:"size"`
	Modified    int64  `json:"modified"`
	Permissions string `json:"permissions"`
	Path        string `json:"path"`
}
